version: '3.3'

services: 
  postgres:
    image: postgres:16.1
    container_name: postgres_django
    restart: always
    environment:
      - POSTGRES_DB=trelloapp
      - POSTGRES_USER=trelloapp
      - POSTGRES_PASSWORD=trellopass
    volumes:
      - ./db/init.sql:/docker-entrypoint.initdb.d/init.sql
    ports:
      - '5432:5432'  

  redis:
    container_name: redis_django
    image: redis:7
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

volumes:
  redis:
