# Generated by Django 4.2.7 on 2023-12-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trelloApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='dueDate',
            field=models.DateTimeField(),
        ),
    ]
